# This is a basic workflow to help you get started with Actions

name: Meu Primeiro CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build_teste:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Primeira task
        run: echo Executa o primeiro comando no Linux!

      # Runs a set of commands using the runners shell
      - name: Segunda Task
        run: |
          echo Executa segundo comando no shell
          ls
